[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_amm_project = "EuB1XVzgMPt1bFYY1wW3hcNAZEuT4y4qWiTH7n8j3Pz5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/test_1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
